# Generated by Django 5.1 on 2024-08-15 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_alter_investment_date'),
        ('outflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inflow',
            new_name='Outflow',
        ),
    ]
