# Generated by Django 5.1 on 2024-08-19 19:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflow', '0002_rename_inflow_outflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='outflow',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
