# Generated by Django 5.1 on 2024-08-19 19:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflow', '0003_outflow_amount_alter_outflow_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outflow',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
