# Generated by Django 5.1 on 2024-08-20 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0008_alter_investment_investment_type'),
        ('outflow', '0004_alter_outflow_created_at_alter_outflow_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outflow',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outflows', to='investment.investment'),
        ),
    ]
