# Generated by Django 5.1 on 2024-08-12 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('symbol', models.CharField(max_length=20)),
                ('operation', models.CharField(choices=[('buy', 'Compra'), ('sell', 'Venda')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('investment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='type.type')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
