# Generated by Django 5.1 on 2024-08-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
