# Generated by Django 5.1 on 2024-08-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_remove_investment_date_investment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
