# Generated by Django 5.1 on 2024-08-20 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0007_alter_investment_amount'),
        ('type', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='investment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='type.type'),
        ),
    ]
