# Generated by Django 5.1 on 2024-08-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0002_alter_inflow_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflow',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
