# Generated by Django 5.1 on 2024-08-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0003_inflow_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
