# Generated by Django 5.1 on 2024-08-20 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0005_alter_inflow_created_at_alter_inflow_updated_at'),
        ('investment', '0008_alter_investment_investment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inflows', to='investment.investment'),
        ),
    ]
