# Generated by Django 5.1 on 2024-08-12 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dividend', '0001_initial'),
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investment.investment'),
        ),
    ]
