# Generated by Django 5.1 on 2024-08-15 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dividend', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dividend',
            options={'ordering': ['name']},
        ),
    ]
