# Generated by Django 5.1 on 2024-08-19 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dividend', '0003_alter_dividend_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dividend',
            old_name='amount_per_share',
            new_name='total_dividends',
        ),
    ]
